FROM mariadb
# Add a database
ENV MYSQL_DATABASE testdb
ENV MYSQL_ROOT_PASSWORD example
ENV MYSQL_DATABASE friend
ENV MYSQL_USER m1s2TpProg
ENV MYSQL_PASSWORD l@Cath0M1s2
COPY ./sql /docker-entrypoint-initdb.d
EXPOSE 3306